### ISSUE TITLE
improve website content

### ISSUE THREAD

**Issue by rutsam** [MBAZA-NLP/community.website#10]
Goal: improve website content

**Definition of Done**
- [ ] Remove dummy data from the website
- [ ] Update mbaza-nlp contact information to the website (change bottom section)

**Comment by rutsam** [comment]
Olivier will push the latest changes

**Comment by twist250** [comment]
- [ ] Replace programs with Quick links
- [ ] Move Follow Us into bottom footer
- [ ] Change color `Quick Links` title to white
